osx_image: xcode8.1
language: objective-c
rvm:
  - 2.2
before_install:
- gem install bundler -v '>= 1.13.4' --no-doc
- gem install scan --no-doc
- gem install cocoapods --no-doc
script:
- set -o pipefail && scan --project 'Waxwing/Waxwing.xcodeproj'
# - pod lib lint
