osx_image: xcode8.0
language: objective-c
rvm:
  - 2.2
before_install:
- gem install scan --no-doc
- gem install cocoapods --no-doc
script:
- set -o pipefail && scan --project 'Waxwing/Waxwing.xcodeproj'
# - pod lib lint
